import type { UiStyles } from '../types/ui';

export const uiStyles: UiStyles = {
  container: {
    padding: '8px 16px 16px',
    backgroundColor: 'white',
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    color: 'black',
    fontFamily: 'Inter, sans-serif',
    boxSizing: 'border-box' as const,
    overflowX: 'hidden' as const,
  },
  title: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '12px',
    marginTop: '8px',
  },
  tabHeader: {
    display: 'flex',
    width: '100%',
    maxWidth: '320px',
    marginBottom: '8px',
    borderBottom: '1px solid #e5e7eb',
  },
  tabButton: (isActive: boolean) => ({
    flex: 1,
    padding: '10px 0',
    background: 'none',
    border: 'none',
    borderBottom: isActive ? '2px solid #000000' : '2px solid transparent',
    color: isActive ? '#000000' : '#999999',
    fontSize: '13px',
    fontWeight: 700 as const,
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
    letterSpacing: '0.5px',
  }),
  contentArea: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
    width: '100%',
    overflowY: 'auto' as const,
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
    width: '100%',
    maxWidth: '320px',
    flex: 1,
  },
  label: {
    fontSize: '14px',
    fontWeight: 600,
    marginBottom: '4px',
  },
  textarea: {
    border: '1px solid #d1d5db',
    borderRadius: '4px',
    padding: '8px',
    color: 'black',
    fontSize: '14px',
    width: '100%',
    boxSizing: 'border-box' as const,
    resize: 'vertical' as const,
    minHeight: '140px',
    fontFamily: 'Inter, sans-serif',
  },
  inputWrapper: {
    position: 'relative' as const,
    width: '100%',
  },
  buttonEnhance: {
    backgroundColor: 'transparent',
    color: '#333333',
    border: '1px solid #d1d5db',
    borderRadius: '4px',
    padding: '9px 12px',
    fontSize: '12px',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
    whiteSpace: 'nowrap' as const,
    boxSizing: 'border-box' as const,
  },
  buttonPrimary: {
    backgroundColor: 'black',
    color: 'white',
    borderRadius: '4px',
    padding: '10px',
    marginTop: '8px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 500,
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  buttonSecondary: {
    color: '#6b7280',
    fontSize: '12px',
    marginTop: '8px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'center' as const,
  },
  previewContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    maxWidth: '320px',
  },
  previewImage: {
    width: '100%',
    borderRadius: '6px',
    border: '2px solid #000000',
  },
  previewButtonRow: {
    display: 'flex',
    gap: '8px',
    width: '100%',
  },
  buttonApply: {
    flex: 1,
    backgroundColor: '#000000',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
  },
  buttonRetry: {
    flex: 1,
    backgroundColor: 'transparent',
    color: '#6b7280',
    border: '1px solid #d1d5db',
    borderRadius: '4px',
    padding: '10px',
    fontSize: '13px',
    fontWeight: 500,
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
  },
  selectionZone: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '320px',
    minHeight: '200px',
    border: '2px dashed #333333',
    borderRadius: '8px',
    backgroundColor: '#111111',
    color: '#666666',
    fontSize: '14px',
    gap: '8px',
  },
  selectionZoneIcon: {
    fontSize: '32px',
  },
  selectionZoneText: {
    fontStyle: 'italic' as const,
    textAlign: 'center' as const,
    padding: '0 20px',
    lineHeight: '1.5',
  },
  editPreviewContainer: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
    width: '100%',
    maxWidth: '100%',
    boxSizing: 'border-box' as const,
    overflowX: 'hidden' as const,
  },
  editImageWrapper: {
    position: 'relative' as const,
    width: '100%',
  },
  editImage: {
    width: '100%',
    borderRadius: '6px',
    border: '2px solid #000000',
    display: 'block' as const,
  },
  editCloseButton: {
    position: 'absolute' as const,
    top: '8px',
    right: '8px',
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    color: '#ffffff',
    border: '1px solid #333',
    fontSize: '14px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    lineHeight: 1,
  },
  editActionRow: {
    display: 'flex',
    gap: '6px',
    width: '100%',
  },
  editActionButton: {
    flex: 1,
    backgroundColor: '#000000',
    color: '#ffffff',
    border: 'none',
    borderRadius: '4px',
    padding: '8px 4px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'Inter, sans-serif',
    textAlign: 'center' as const,
  },
};
